services:
  # Dịch vụ Backend
  backend:
    container_name: hcmut-portal-backend
    build: ./backend # Đường dẫn tới folder chứa Dockerfile backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # Nối cổng 8000 của Docker ra 8000 của máy thật
    env_file:
      - .env
    environment:
      IS_DOCKER: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips='*'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
        - path: ./backend
          action: sync
          target: /migrations

  # Database Service (Postgres)
  db:
    image: postgres:15-alpine
    container_name: hcmut-portal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
    # Remember to change your port here, always keep the 5432 at the end, only change the number before it !
      - "5434:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 15s
      retries: 10

  # Dịch vụ Frontend
  frontend:
    container_name: hcmut-portal-frontend
    build: ./frontend # Đường dẫn tới folder chứa Dockerfile frontend
    ports:
      - "3000:3000" # Nối cổng 3000 của Docker ra 3000 của máy thật

    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=1
      # Cái này quan trọng:
      # Khi chạy trong Docker, Frontend cần biết Backend ở đâu.
      # Nếu client (trình duyệt) gọi -> vẫn là localhost:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - BACKEND_URL=http://hcmut-portal-backend:8000
      - INTERNAL_API_URL=http://hcmut-portal-backend:8000
    depends_on:
      - backend # Chờ backend chạy xong mới chạy frontend
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/

  # Dịch vụ Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
