"""Add scholarship table

Revision ID: 0d91b699fe50
Revises: e62d8a264f71
Create Date: 2026-04-05 06:34:19.033679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d91b699fe50'
down_revision: Union[str, Sequence[str], None] = 'e62d8a264f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('gpa_4_condition', sa.Float(), nullable=True),
    sa.Column('gpa_10_condition', sa.Float(), nullable=True),
    sa.Column('training_point_condition', sa.Float(), nullable=True),
    sa.Column('scholarship_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_scholarships_id'), 'student_scholarships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_scholarships_id'), table_name='student_scholarships')
    op.drop_table('student_scholarships')
    # ### end Alembic commands ###
