"""change the link of the finnace table to indenties

Revision ID: 0e26c6cdd926
Revises: 83c9c0e58fcd
Create Date: 2026-03-13 14:56:03.658142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e26c6cdd926'
down_revision: Union[str, Sequence[str], None] = '83c9c0e58fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_academics', 'bank_account')
    op.drop_column('student_academics', 'bank_name')
    op.drop_column('student_academics', 'ocb_cif')
    op.drop_column('student_academics', 'bknet_account')
    op.add_column('student_finances', sa.Column('identity_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_finances_academic_id_key'), 'student_finances', type_='unique')
    op.create_unique_constraint(None, 'student_finances', ['identity_id'])
    op.drop_constraint(op.f('student_finances_academic_id_fkey'), 'student_finances', type_='foreignkey')
    op.create_foreign_key(None, 'student_finances', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_finances', 'academic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_finances', sa.Column('academic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_finances', type_='foreignkey')
    op.create_foreign_key(op.f('student_finances_academic_id_fkey'), 'student_finances', 'student_academics', ['academic_id'], ['id'])
    op.drop_constraint(None, 'student_finances', type_='unique')
    op.create_unique_constraint(op.f('student_finances_academic_id_key'), 'student_finances', ['academic_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_finances', 'identity_id')
    op.add_column('student_academics', sa.Column('bknet_account', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('ocb_cif', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('bank_account', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
