"""delete string piority group col

Revision ID: 31ba6b636474
Revises: b4dcddecb6ae
Create Date: 2026-01-08 22:23:25.894347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ba6b636474'
down_revision: Union[str, Sequence[str], None] = 'b4dcddecb6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_personals', 'priority_object')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_personals', sa.Column('priority_object', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
