"""add_academic_performance_module

Revision ID: 6ceb713ce948
Revises: 12f672cf062b
Create Date: 2026-04-09 14:42:00.999698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ceb713ce948'
down_revision: Union[str, Sequence[str], None] = '12f672cf062b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_components_id'), 'course_components', ['id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('semester_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_anchor_id'), 'enrollments', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_semester_id'), 'enrollments', ['semester_id'], unique=False)
    op.create_table('scholarship_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', name='scholarshipstatus'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], ),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_recipients_anchor_id'), 'scholarship_recipients', ['anchor_id'], unique=False)
    op.create_index(op.f('ix_scholarship_recipients_id'), 'scholarship_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_scholarship_recipients_semester_id'), 'scholarship_recipients', ['semester_id'], unique=False)
    op.create_table('semester_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('final_grade_10', sa.Float(), nullable=False),
    sa.Column('final_grade_4', sa.Float(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_semester_results_id'), 'semester_results', ['id'], unique=False)
    op.create_table('student_component_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('raw_grade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['course_components.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_component_grades_enrollment_id'), 'student_component_grades', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_student_component_grades_id'), 'student_component_grades', ['id'], unique=False)
    op.add_column('courses', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'faculties', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'faculty_id')
    op.drop_index(op.f('ix_student_component_grades_id'), table_name='student_component_grades')
    op.drop_index(op.f('ix_student_component_grades_enrollment_id'), table_name='student_component_grades')
    op.drop_table('student_component_grades')
    op.drop_index(op.f('ix_semester_results_id'), table_name='semester_results')
    op.drop_table('semester_results')
    op.drop_index(op.f('ix_scholarship_recipients_semester_id'), table_name='scholarship_recipients')
    op.drop_index(op.f('ix_scholarship_recipients_id'), table_name='scholarship_recipients')
    op.drop_index(op.f('ix_scholarship_recipients_anchor_id'), table_name='scholarship_recipients')
    op.drop_table('scholarship_recipients')
    op.drop_index(op.f('ix_enrollments_semester_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_anchor_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_course_components_id'), table_name='course_components')
    op.drop_table('course_components')
    # ### end Alembic commands ###
