"""clean_start_final

Revision ID: 83c9c0e58fcd
Revises: 
Create Date: 2026-01-21 12:53:07.299596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c9c0e58fcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=False),
    sa.Column('decision_number', sa.String(), nullable=False),
    sa.Column('decision_content', sa.String(), nullable=False),
    sa.Column('signed_date', sa.String(), nullable=False),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.Column('decision_type', sa.Enum('IN', 'OTHER', name='decisiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_table('ethnics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_vi', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_vi')
    )
    op.create_index(op.f('ix_ethnics_id'), 'ethnics', ['id'], unique=False)
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en_name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_faculties_id'), 'faculties', ['id'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'LECTURER', 'ADMIN', 'OFFICE', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identities_id'), 'identities', ['id'], unique=False)
    op.create_table('management_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_management_units_id'), 'management_units', ['id'], unique=False)
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('religions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_vi', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_vi')
    )
    op.create_index(op.f('ix_religions_id'), 'religions', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('general_informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('id_card_number', sa.String(length=20), nullable=True),
    sa.Column('id_card_date', sa.Date(), nullable=True),
    sa.Column('id_card_place', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('personal_email', sa.String(length=100), nullable=True),
    sa.Column('backup_email', sa.String(length=100), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('other_place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.Column('ethnic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'GRADUATED', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['ethnic_id'], ['ethnics.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['nationality_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_general_informations_id'), 'general_informations', ['id'], unique=False)
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_majors_id'), 'majors', ['id'], unique=False)
    op.create_table('student_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_decisions_id'), 'student_decisions', ['id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('relationship_to_student', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('citizen_id', sa.String(length=50), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_student_guardians_id'), 'student_guardians', ['id'], unique=False)
    op.create_table('student_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('father_birthday', sa.Date(), nullable=True),
    sa.Column('father_phone', sa.String(length=20), nullable=True),
    sa.Column('father_job', sa.String(length=255), nullable=True),
    sa.Column('father_workplace', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('mother_birthday', sa.Date(), nullable=True),
    sa.Column('mother_phone', sa.String(length=20), nullable=True),
    sa.Column('mother_job', sa.String(length=255), nullable=True),
    sa.Column('mother_workplace', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_student_parents_id'), 'student_parents', ['id'], unique=False)
    op.create_table('student_personals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=True),
    sa.Column('dorm_room', sa.String(length=50), nullable=True),
    sa.Column('family_phone', sa.String(length=20), nullable=True),
    sa.Column('priority_area', sa.Enum('KV1', 'KV2', 'KV2_NT', 'KV3', name='priorityarea'), nullable=True),
    sa.Column('priority_group', sa.Enum('UT1', 'UT2', 'NONE', name='prioritygroup'), nullable=True),
    sa.Column('union_date', sa.Date(), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=True),
    sa.Column('youth_union_date', sa.Date(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_student_personals_id'), 'student_personals', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.Enum('PERMANENT', 'CURRENT', 'HOMETOWN', 'GUARDIAN', name='addresstype'), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'address_type', name='_identity_address_type_uc')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('student_academics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('class_code', sa.String(length=20), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('curriculum_year', sa.Integer(), nullable=True),
    sa.Column('entry_semester', sa.String(length=20), nullable=True),
    sa.Column('study_duration_standard', sa.String(length=50), nullable=True),
    sa.Column('extended_semesters', sa.Integer(), nullable=True),
    sa.Column('reduced_semesters', sa.Integer(), nullable=True),
    sa.Column('standard_semesters', sa.Integer(), nullable=True),
    sa.Column('max_semesters', sa.Integer(), nullable=True),
    sa.Column('expected_graduation_date', sa.Date(), nullable=True),
    sa.Column('max_graduation_date', sa.Date(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('training_system', sa.String(length=100), nullable=True),
    sa.Column('training_type', sa.String(length=100), nullable=True),
    sa.Column('program', sa.String(length=200), nullable=True),
    sa.Column('campus', sa.String(length=200), nullable=True),
    sa.Column('local_training', sa.String(length=200), nullable=True),
    sa.Column('training_session', sa.String(length=50), nullable=True),
    sa.Column('student_status', sa.String(length=50), nullable=True),
    sa.Column('grad_major', sa.String(length=150), nullable=True),
    sa.Column('grad_year_semester', sa.String(length=50), nullable=True),
    sa.Column('grad_decision_number', sa.String(length=50), nullable=True),
    sa.Column('grad_decision_date', sa.Date(), nullable=True),
    sa.Column('bknet_account', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('ocb_cif', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['management_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_student_academics_id'), 'student_academics', ['id'], unique=False)
    op.create_index(op.f('ix_student_academics_student_code'), 'student_academics', ['student_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_academics_student_code'), table_name='student_academics')
    op.drop_index(op.f('ix_student_academics_id'), table_name='student_academics')
    op.drop_table('student_academics')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('wards')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_student_personals_id'), table_name='student_personals')
    op.drop_table('student_personals')
    op.drop_index(op.f('ix_student_parents_id'), table_name='student_parents')
    op.drop_table('student_parents')
    op.drop_index(op.f('ix_student_guardians_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_student_decisions_id'), table_name='student_decisions')
    op.drop_table('student_decisions')
    op.drop_index(op.f('ix_majors_id'), table_name='majors')
    op.drop_table('majors')
    op.drop_index(op.f('ix_general_informations_id'), table_name='general_informations')
    op.drop_table('general_informations')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_religions_id'), table_name='religions')
    op.drop_table('religions')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_management_units_id'), table_name='management_units')
    op.drop_table('management_units')
    op.drop_index(op.f('ix_identities_id'), table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_faculties_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_ethnics_id'), table_name='ethnics')
    op.drop_table('ethnics')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('countries')
    # ### end Alembic commands ###
