"""Make health insurance generic

Revision ID: 8411d468d674
Revises: bcfa1397e72f
Create Date: 2026-04-10 05:08:02.350159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8411d468d674'
down_revision: Union[str, Sequence[str], None] = 'bcfa1397e72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('medical_book_number', sa.String(length=50), nullable=True),
    sa.Column('health_insurance_number', sa.String(length=50), nullable=True),
    sa.Column('accident_insurance_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_insurances_id'), 'health_insurances', ['id'], unique=False)
    op.create_index(op.f('ix_health_insurances_identity_id'), 'health_insurances', ['identity_id'], unique=True)
    op.drop_index(op.f('ix_student_health_insurances_anchor_id'), table_name='student_health_insurances')
    op.drop_index(op.f('ix_student_health_insurances_id'), table_name='student_health_insurances')
    op.drop_table('student_health_insurances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_health_insurances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anchor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medical_book_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('health_insurance_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accident_insurance_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], name=op.f('student_health_insurances_anchor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_health_insurances_pkey'))
    )
    op.create_index(op.f('ix_student_health_insurances_id'), 'student_health_insurances', ['id'], unique=False)
    op.create_index(op.f('ix_student_health_insurances_anchor_id'), 'student_health_insurances', ['anchor_id'], unique=True)
    op.drop_index(op.f('ix_health_insurances_identity_id'), table_name='health_insurances')
    op.drop_index(op.f('ix_health_insurances_id'), table_name='health_insurances')
    op.drop_table('health_insurances')
    # ### end Alembic commands ###
