"""Move student sub-models to reference StudentRoleAnchor

Revision ID: 8440ab4e69ae
Revises: bbfc60ca2dfd
Create Date: 2026-03-14 03:23:11.854510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8440ab4e69ae'
down_revision: Union[str, Sequence[str], None] = 'bbfc60ca2dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_graduations', sa.Column('anchor_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_graduations_identity_id_key'), 'student_graduations', type_='unique')
    op.create_unique_constraint(None, 'student_graduations', ['anchor_id'])
    op.drop_constraint(op.f('student_graduations_identity_id_fkey'), 'student_graduations', type_='foreignkey')
    op.create_foreign_key(None, 'student_graduations', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_graduations', 'identity_id')
    op.add_column('student_programs', sa.Column('anchor_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_programs_identity_id_key'), 'student_programs', type_='unique')
    op.create_unique_constraint(None, 'student_programs', ['anchor_id'])
    op.drop_constraint(op.f('student_programs_identity_id_fkey'), 'student_programs', type_='foreignkey')
    op.create_foreign_key(None, 'student_programs', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_programs', 'identity_id')
    op.create_unique_constraint(None, 'student_role_anchors', ['identity_id'])
    op.add_column('student_timelines', sa.Column('anchor_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_timelines_identity_id_key'), 'student_timelines', type_='unique')
    op.create_unique_constraint(None, 'student_timelines', ['anchor_id'])
    op.drop_constraint(op.f('student_timelines_identity_id_fkey'), 'student_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'student_timelines', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_timelines', 'identity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_timelines', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('student_timelines_identity_id_fkey'), 'student_timelines', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_timelines', type_='unique')
    op.create_unique_constraint(op.f('student_timelines_identity_id_key'), 'student_timelines', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_timelines', 'anchor_id')
    op.drop_constraint(None, 'student_role_anchors', type_='unique')
    op.add_column('student_programs', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_programs', type_='foreignkey')
    op.create_foreign_key(op.f('student_programs_identity_id_fkey'), 'student_programs', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_programs', type_='unique')
    op.create_unique_constraint(op.f('student_programs_identity_id_key'), 'student_programs', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_programs', 'anchor_id')
    op.add_column('student_graduations', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_graduations', type_='foreignkey')
    op.create_foreign_key(op.f('student_graduations_identity_id_fkey'), 'student_graduations', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_graduations', type_='unique')
    op.create_unique_constraint(op.f('student_graduations_identity_id_key'), 'student_graduations', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_graduations', 'anchor_id')
    # ### end Alembic commands ###
