"""Move scholarship to adminstrative

Revision ID: 8ce41c85f4ff
Revises: 0d91b699fe50
Create Date: 2026-04-05 06:40:31.972701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce41c85f4ff'
down_revision: Union[str, Sequence[str], None] = '0d91b699fe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gpa_4_condition', sa.Float(), nullable=False),
    sa.Column('gpa_10_condition', sa.Float(), nullable=False),
    sa.Column('training_point_condition', sa.Integer(), nullable=False),
    sa.Column('scholarship_percentage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.drop_index(op.f('ix_student_scholarships_id'), table_name='student_scholarships')
    op.drop_table('student_scholarships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_scholarships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anchor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gpa_4_condition', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpa_10_condition', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('training_point_condition', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scholarship_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], name=op.f('student_scholarships_anchor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_scholarships_pkey'))
    )
    op.create_index(op.f('ix_student_scholarships_id'), 'student_scholarships', ['id'], unique=False)
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    # ### end Alembic commands ###
