"""Add ProfileUpdateRequest model

Revision ID: 9e41db37f931
Revises: 8411d468d674
Create Date: 2026-04-09 22:25:30.712029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e41db37f931'
down_revision: Union[str, Sequence[str], None] = '8411d468d674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_update_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HEALTH_INSURANCE', 'GENERAL_INFORMATION', name='requesttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('requested_data', sa.JSON(), nullable=False),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('admin_comment', sa.String(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_update_requests_id'), 'profile_update_requests', ['id'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_identity_id'), 'profile_update_requests', ['identity_id'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_status'), 'profile_update_requests', ['status'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_type'), 'profile_update_requests', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_update_requests_type'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_status'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_identity_id'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_id'), table_name='profile_update_requests')
    op.drop_table('profile_update_requests')
    # ### end Alembic commands ###
