"""delete duplicated relate to student col

Revision ID: b4dcddecb6ae
Revises: e88d11d1f286
Create Date: 2026-01-08 22:13:14.821339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dcddecb6ae'
down_revision: Union[str, Sequence[str], None] = 'e88d11d1f286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_guardians', 'relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_guardians', sa.Column('relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
