"""remove redundant academic fields

Revision ID: b6a8148b608b
Revises: d4735c2d7282
Create Date: 2026-03-14 01:31:13.494642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a8148b608b'
down_revision: Union[str, Sequence[str], None] = 'd4735c2d7282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_academics', 'enrollment_date')
    op.drop_column('student_academics', 'program')
    op.drop_column('student_academics', 'entry_semester')
    op.drop_column('student_academics', 'grad_major')
    op.drop_column('student_academics', 'study_duration_standard')
    op.drop_column('student_academics', 'standard_semesters')
    op.drop_column('student_academics', 'education_level')
    op.drop_column('student_academics', 'campus')
    op.drop_column('student_academics', 'max_graduation_date')
    op.drop_column('student_academics', 'grad_decision_number')
    op.drop_column('student_academics', 'curriculum_year')
    op.drop_column('student_academics', 'grad_decision_date')
    op.drop_column('student_academics', 'extended_semesters')
    op.drop_column('student_academics', 'max_semesters')
    op.drop_column('student_academics', 'training_session')
    op.drop_column('student_academics', 'reduced_semesters')
    op.drop_column('student_academics', 'expected_graduation_date')
    op.drop_column('student_academics', 'local_training')
    op.drop_column('student_academics', 'training_type')
    op.drop_column('student_academics', 'student_status')
    op.drop_column('student_academics', 'grad_year_semester')
    op.drop_column('student_academics', 'training_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_academics', sa.Column('training_system', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('grad_year_semester', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('student_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('training_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('local_training', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('expected_graduation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('reduced_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('training_session', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('max_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('extended_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('grad_decision_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('curriculum_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('grad_decision_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('max_graduation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('campus', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('standard_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('study_duration_standard', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('grad_major', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('entry_semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('program', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('student_academics', sa.Column('enrollment_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
