"""Add StudentRoleAnchor and AcademicBatch models

Revision ID: bbfc60ca2dfd
Revises: b6a8148b608b
Create Date: 2026-03-14 03:16:00.760733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfc60ca2dfd'
down_revision: Union[str, Sequence[str], None] = 'b6a8148b608b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academics_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=50), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_name')
    )
    op.create_index(op.f('ix_academics_batch_id'), 'academics_batch', ['id'], unique=False)
    op.create_table('student_role_anchors',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(length=20), nullable=False),
    sa.Column('student_status', sa.String(length=50), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['academics_batch.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['management_units.id'], ),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('identity_id')
    )
    op.create_index(op.f('ix_student_role_anchors_student_code'), 'student_role_anchors', ['student_code'], unique=True)
    op.add_column('faculties', sa.Column('standard_semesters', sa.Integer(), nullable=True))
    op.add_column('faculties', sa.Column('extended_semesters', sa.Integer(), nullable=True))
    op.add_column('student_programs', sa.Column('major_id', sa.Integer(), nullable=True))
    op.add_column('student_programs', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_programs', 'management_units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'student_programs', 'majors', ['major_id'], ['id'])
    op.drop_column('student_timelines', 'extended_semesters')
    op.drop_column('student_timelines', 'standard_semesters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_timelines', sa.Column('standard_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_timelines', sa.Column('extended_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_programs', type_='foreignkey')
    op.drop_constraint(None, 'student_programs', type_='foreignkey')
    op.drop_column('student_programs', 'unit_id')
    op.drop_column('student_programs', 'major_id')
    op.drop_column('faculties', 'extended_semesters')
    op.drop_column('faculties', 'standard_semesters')
    op.drop_index(op.f('ix_student_role_anchors_student_code'), table_name='student_role_anchors')
    op.drop_table('student_role_anchors')
    op.drop_index(op.f('ix_academics_batch_id'), table_name='academics_batch')
    op.drop_table('academics_batch')
    # ### end Alembic commands ###
