"""Add StudentHealthInsurance table

Revision ID: bcfa1397e72f
Revises: fc96dcee62af
Create Date: 2026-04-10 05:00:09.637455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfa1397e72f'
down_revision: Union[str, Sequence[str], None] = 'fc96dcee62af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_health_insurances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('medical_book_number', sa.String(length=50), nullable=True),
    sa.Column('health_insurance_number', sa.String(length=50), nullable=True),
    sa.Column('accident_insurance_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['student_role_anchors.identity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_health_insurances_anchor_id'), 'student_health_insurances', ['anchor_id'], unique=True)
    op.create_index(op.f('ix_student_health_insurances_id'), 'student_health_insurances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_health_insurances_id'), table_name='student_health_insurances')
    op.drop_index(op.f('ix_student_health_insurances_anchor_id'), table_name='student_health_insurances')
    op.drop_table('student_health_insurances')
    # ### end Alembic commands ###
