"""update foreign keys for graduation timeline program to identity

Revision ID: d4735c2d7282
Revises: 26fc96802cf1
Create Date: 2026-03-13 23:48:44.114296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4735c2d7282'
down_revision: Union[str, Sequence[str], None] = '26fc96802cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_graduations', sa.Column('identity_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_graduations_academic_id_key'), 'student_graduations', type_='unique')
    op.create_unique_constraint(None, 'student_graduations', ['identity_id'])
    op.drop_constraint(op.f('student_graduations_academic_id_fkey'), 'student_graduations', type_='foreignkey')
    op.create_foreign_key(None, 'student_graduations', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_graduations', 'academic_id')
    op.add_column('student_programs', sa.Column('identity_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_programs_academic_id_key'), 'student_programs', type_='unique')
    op.create_unique_constraint(None, 'student_programs', ['identity_id'])
    op.drop_constraint(op.f('student_programs_academic_id_fkey'), 'student_programs', type_='foreignkey')
    op.create_foreign_key(None, 'student_programs', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_programs', 'academic_id')
    op.add_column('student_timelines', sa.Column('identity_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('student_timelines_academic_id_key'), 'student_timelines', type_='unique')
    op.create_unique_constraint(None, 'student_timelines', ['identity_id'])
    op.drop_constraint(op.f('student_timelines_academic_id_fkey'), 'student_timelines', type_='foreignkey')
    op.create_foreign_key(None, 'student_timelines', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_timelines', 'academic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_timelines', sa.Column('academic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_timelines', type_='foreignkey')
    op.create_foreign_key(op.f('student_timelines_academic_id_fkey'), 'student_timelines', 'student_academics', ['academic_id'], ['id'])
    op.drop_constraint(None, 'student_timelines', type_='unique')
    op.create_unique_constraint(op.f('student_timelines_academic_id_key'), 'student_timelines', ['academic_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_timelines', 'identity_id')
    op.add_column('student_programs', sa.Column('academic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_programs', type_='foreignkey')
    op.create_foreign_key(op.f('student_programs_academic_id_fkey'), 'student_programs', 'student_academics', ['academic_id'], ['id'])
    op.drop_constraint(None, 'student_programs', type_='unique')
    op.create_unique_constraint(op.f('student_programs_academic_id_key'), 'student_programs', ['academic_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_programs', 'identity_id')
    op.add_column('student_graduations', sa.Column('academic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_graduations', type_='foreignkey')
    op.create_foreign_key(op.f('student_graduations_academic_id_fkey'), 'student_graduations', 'student_academics', ['academic_id'], ['id'])
    op.drop_constraint(None, 'student_graduations', type_='unique')
    op.create_unique_constraint(op.f('student_graduations_academic_id_key'), 'student_graduations', ['academic_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_graduations', 'identity_id')
    # ### end Alembic commands ###
