"""add country data

Revision ID: e88d11d1f286
Revises: 
Create Date: 2026-01-08 22:01:36.183083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88d11d1f286'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_guardians', sa.Column('relationship', sa.String(length=100), nullable=True))
    op.add_column('student_guardians', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('student_guardians', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.add_column('student_guardians', sa.Column('house_number', sa.String(length=50), nullable=True))
    op.alter_column('student_guardians', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'student_guardians', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'student_guardians', 'wards', ['ward_id'], ['id'])
    op.alter_column('student_parents', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('student_personals', sa.Column('dorm_room', sa.String(length=50), nullable=True))
    op.add_column('student_personals', sa.Column('family_phone', sa.String(length=20), nullable=True))
    op.add_column('student_personals', sa.Column('priority_group', sa.Enum('UT1', 'UT2', 'NONE', name='prioritygroup'), nullable=True))
    op.alter_column('student_personals', 'priority_area',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('KV1', 'KV2', 'KV2_NT', 'KV3', name='priorityarea'),
               postgresql_using='priority_area::priorityarea',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_personals', 'priority_area',
               existing_type=sa.Enum('KV1', 'KV2', 'KV2_NT', 'KV3', name='priorityarea'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('student_personals', 'priority_group')
    op.drop_column('student_personals', 'family_phone')
    op.drop_column('student_personals', 'dorm_room')
    op.alter_column('student_parents', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'student_guardians', type_='foreignkey')
    op.drop_constraint(None, 'student_guardians', type_='foreignkey')
    op.alter_column('student_guardians', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('student_guardians', 'house_number')
    op.drop_column('student_guardians', 'ward_id')
    op.drop_column('student_guardians', 'province_id')
    op.drop_column('student_guardians', 'relationship')
    # ### end Alembic commands ###
