"""Rename Student Decision table

Revision ID: fb73e4b77110
Revises: eceac7caf450
Create Date: 2026-01-18 15:57:43.299500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb73e4b77110'
down_revision: Union[str, Sequence[str], None] = 'eceac7caf450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=False),
    sa.Column('decision_number', sa.String(), nullable=False),
    sa.Column('decision_content', sa.String(), nullable=False),
    sa.Column('signed_date', sa.String(), nullable=False),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.Column('decision_type', sa.Enum('IN', 'OTHER', name='decisiontype'), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_decisions_id'), 'student_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('signed_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_updated', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('decision_type', postgresql.ENUM('IN', 'OTHER', name='decisiontype'), autoincrement=False, nullable=False),
    sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], name=op.f('decisions_identity_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decisions_pkey'))
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.drop_index(op.f('ix_student_decisions_id'), table_name='student_decisions')
    op.drop_table('student_decisions')
    # ### end Alembic commands ###
