"""add_snapshot_fields_to_scholarship

Revision ID: fc96dcee62af
Revises: 6ceb713ce948
Create Date: 2026-04-09 15:30:27.028918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc96dcee62af'
down_revision: Union[str, Sequence[str], None] = '6ceb713ce948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_recipients', sa.Column('gpa_4', sa.Float(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('gpa_10', sa.Float(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('cpa_4', sa.Float(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('cpa_10', sa.Float(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('credits_earned', sa.Integer(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('cumulative_credits', sa.Integer(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('training_point', sa.Integer(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('result', sa.String(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('scholarship_recipients', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('scholarship_recipients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('scholarship_recipients', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_recipients', 'updated_by')
    op.drop_column('scholarship_recipients', 'updated_at')
    op.drop_column('scholarship_recipients', 'created_by')
    op.drop_column('scholarship_recipients', 'created_at')
    op.drop_column('scholarship_recipients', 'result')
    op.drop_column('scholarship_recipients', 'amount')
    op.drop_column('scholarship_recipients', 'training_point')
    op.drop_column('scholarship_recipients', 'cumulative_credits')
    op.drop_column('scholarship_recipients', 'credits_earned')
    op.drop_column('scholarship_recipients', 'cpa_10')
    op.drop_column('scholarship_recipients', 'cpa_4')
    op.drop_column('scholarship_recipients', 'gpa_10')
    op.drop_column('scholarship_recipients', 'gpa_4')
    # ### end Alembic commands ###
