"""Migrate all student models to StudentRoleAnchor

Revision ID: fd969289292a
Revises: 8440ab4e69ae
Create Date: 2026-03-14 03:32:01.835909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd969289292a'
down_revision: Union[str, Sequence[str], None] = '8440ab4e69ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_academics', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_academics_identity_id_key'), 'student_academics', type_='unique')
    op.create_unique_constraint(None, 'student_academics', ['anchor_id'])
    op.drop_constraint(op.f('student_academics_identity_id_fkey'), 'student_academics', type_='foreignkey')
    op.create_foreign_key(None, 'student_academics', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_academics', 'identity_id')
    op.add_column('student_decisions', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_decisions_identity_id_fkey'), 'student_decisions', type_='foreignkey')
    op.create_foreign_key(None, 'student_decisions', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_decisions', 'identity_id')
    op.add_column('student_extra_curriculars', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_extra_curriculars_identity_id_fkey'), 'student_extra_curriculars', type_='foreignkey')
    op.create_foreign_key(None, 'student_extra_curriculars', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_extra_curriculars', 'identity_id')
    op.add_column('student_finances', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_finances_identity_id_key'), 'student_finances', type_='unique')
    op.create_unique_constraint(None, 'student_finances', ['anchor_id'])
    op.drop_constraint(op.f('student_finances_identity_id_fkey'), 'student_finances', type_='foreignkey')
    op.create_foreign_key(None, 'student_finances', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_finances', 'identity_id')
    op.add_column('student_guardians', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_guardians_identity_id_key'), 'student_guardians', type_='unique')
    op.create_unique_constraint(None, 'student_guardians', ['anchor_id'])
    op.drop_constraint(op.f('student_guardians_identity_id_fkey'), 'student_guardians', type_='foreignkey')
    op.create_foreign_key(None, 'student_guardians', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_guardians', 'identity_id')
    op.add_column('student_parents', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_parents_identity_id_key'), 'student_parents', type_='unique')
    op.create_unique_constraint(None, 'student_parents', ['anchor_id'])
    op.drop_constraint(op.f('student_parents_identity_id_fkey'), 'student_parents', type_='foreignkey')
    op.create_foreign_key(None, 'student_parents', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_parents', 'identity_id')
    op.add_column('student_personals', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_personals_identity_id_key'), 'student_personals', type_='unique')
    op.create_unique_constraint(None, 'student_personals', ['anchor_id'])
    op.drop_constraint(op.f('student_personals_identity_id_fkey'), 'student_personals', type_='foreignkey')
    op.create_foreign_key(None, 'student_personals', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_personals', 'identity_id')
    op.add_column('student_training_points', sa.Column('anchor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('student_training_points_identity_id_fkey'), 'student_training_points', type_='foreignkey')
    op.create_foreign_key(None, 'student_training_points', 'student_role_anchors', ['anchor_id'], ['identity_id'])
    op.drop_column('student_training_points', 'identity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_training_points', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_training_points', type_='foreignkey')
    op.create_foreign_key(op.f('student_training_points_identity_id_fkey'), 'student_training_points', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_training_points', 'anchor_id')
    op.add_column('student_personals', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_personals', type_='foreignkey')
    op.create_foreign_key(op.f('student_personals_identity_id_fkey'), 'student_personals', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_personals', type_='unique')
    op.create_unique_constraint(op.f('student_personals_identity_id_key'), 'student_personals', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_personals', 'anchor_id')
    op.add_column('student_parents', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_parents', type_='foreignkey')
    op.create_foreign_key(op.f('student_parents_identity_id_fkey'), 'student_parents', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_parents', type_='unique')
    op.create_unique_constraint(op.f('student_parents_identity_id_key'), 'student_parents', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_parents', 'anchor_id')
    op.add_column('student_guardians', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_guardians', type_='foreignkey')
    op.create_foreign_key(op.f('student_guardians_identity_id_fkey'), 'student_guardians', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_guardians', type_='unique')
    op.create_unique_constraint(op.f('student_guardians_identity_id_key'), 'student_guardians', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_guardians', 'anchor_id')
    op.add_column('student_finances', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_finances', type_='foreignkey')
    op.create_foreign_key(op.f('student_finances_identity_id_fkey'), 'student_finances', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_finances', type_='unique')
    op.create_unique_constraint(op.f('student_finances_identity_id_key'), 'student_finances', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_finances', 'anchor_id')
    op.add_column('student_extra_curriculars', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_extra_curriculars', type_='foreignkey')
    op.create_foreign_key(op.f('student_extra_curriculars_identity_id_fkey'), 'student_extra_curriculars', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_extra_curriculars', 'anchor_id')
    op.add_column('student_decisions', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_decisions', type_='foreignkey')
    op.create_foreign_key(op.f('student_decisions_identity_id_fkey'), 'student_decisions', 'identities', ['identity_id'], ['id'])
    op.drop_column('student_decisions', 'anchor_id')
    op.add_column('student_academics', sa.Column('identity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_academics', type_='foreignkey')
    op.create_foreign_key(op.f('student_academics_identity_id_fkey'), 'student_academics', 'identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'student_academics', type_='unique')
    op.create_unique_constraint(op.f('student_academics_identity_id_key'), 'student_academics', ['identity_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_academics', 'anchor_id')
    # ### end Alembic commands ###
